### ISSUE TITLE
Support for Ubuntu 22.04?

### ISSUE THREAD

**Issue by rien88** [CodexLabsLLC/Colosseum#94]
### Overview:
Update the build.sh to work with Ubuntu 22.04.

### Smaller Details: 
There seem to be header files missing even when I updated clang to 14 in the build.sh. I also changed `vulkan-utils` to `vulkan-tools` in `setup.sh`, which appears to be the new name of this package for ubuntu 22.

### Nature of Request:  
- Addition

## Why would this feature be useful?
Because Ubuntu 20.04 is now 4 years out of date and it isn't reasonable to expect folks to be using such an old OS.

Here is the bottom lines of the output I get from running `build.sh`:
```
In file included from /home/erinl/src/Colosseum/MavLinkCom/src/MavLinkMessageBase.cpp:13:
/home/erinl/src/Colosseum/MavLinkCom/include/MavLinkConnection.hpp:7:10: fatal error: 'functional' file not found
#include <functional>
         ^~~~~~~~~~~~
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:174: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/MavLinkMessages.cpp.o] Error 1
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:356: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/impl/MavLinkVideoStreamImpl.cpp.o] Error 1
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:104: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/AdHocConnection.cpp.o] Error 1
1 error generated.
1 error generated.
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:230: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/MavLinkVideoStream.cpp.o] Error 1
1 error generated.
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:188: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/MavLinkNode.cpp.o] Error 1
1 error generated.
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:160: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/MavLinkMessageBase.cpp.o] Error 1
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:118: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/MavLinkConnection.cpp.o] Error 1
1 error generated.
1 error generated.
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:314: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/impl/MavLinkNodeImpl.cpp.o] Error 1
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:272: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/impl/AdHocConnectionImpl.cpp.o] Error 1
1 error generated.
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:300: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/impl/MavLinkFtpClientImpl.cpp.o] Error 1
1 error generated.
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:286: MavLinkCom/CMakeFiles/MavLinkCom.dir/home/erinl/src/Colosseum/MavLinkCom/src/impl/MavLinkConnectionImpl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:408: MavLinkCom/CMakeFiles/MavLinkCom.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:76: rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/dispatcher.cc.o] Error 1
1 error generated.
1 error generated.
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:118: rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/this_handler.cc.o] Error 1
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:188: rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/response.cc.o] Error 1
1 error generated.
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:160: rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/rpc_error.cc.o] Error 1
1 error generated.
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:104: rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/client.cc.o] Error 1
1 error generated.
1 error generated.
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:174: rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/detail/server_session.cc.o] Error 1
make[2]: *** [rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/build.make:90: rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/lib/rpc/server.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:355: rpclib_wrapper/rpclib/CMakeFiles/rpc.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by rien88** [comment]
Noting for the record, I forked and made a [branch](https://github.com/robotics-88/Colosseum/tree/feature/ubuntu22) that seems to be working in Ubuntu 22.04. Needs more testing but may make a PR in the future!

**Comment by rien88** [comment]
Update, spoke too soon. It installs and builds, but I think some link isn't working because I can't open BlocksV2. I'm using Unreal 5.4, but I get a message about modules AirSim and BlocksV2 missing. Investigating.

**Comment by nerbivol** [comment]
You don't have to change `vulkan-utils` to `vulkan-tools` in `setup.sh`.  Just run:
```
wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
sudo apt update
```

**Comment by rien88** [comment]
> You don't have to change `vulkan-utils` to `vulkan-tools` in `setup.sh`. Just run:
> 
> ```
> wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
> sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
> sudo apt update
> ```

Good to know! I'll try that next time, I need to set up another ubuntu 22 soon.

**Comment by nerbivol** [comment]
Let us know if you've encountered any configuration issues with ubuntu 22.04

**Comment by xxEoD2242** [comment]
Noted and will put instructions for 22.04 at a later date

**Comment by rien88** [comment]
When I added the vulkan-utils package per @nerbivol 's instructions, I was able to build this version of Colosseum on ubuntu 22, but it still doesn't load Blocks in Unreal. It isn't adding the plugin to the environment, so I manually copied the Plugins folder, then tried to open BlocksV2 and get this error in Unreal:
```
The project could not be compiled. Would you like to open it in Visual Studio Code?

Running /home/erindel/src/UnrealEngine-5.4.0-release/Engine/Build/BatchFiles/Linux/Build.sh Development Linux -Project="/home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/BlocksV2.uproject" -TargetType=Editor -Progress
Setting up bundled DotNet SDK
Running command : dotnet Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll Development Linux -Project=/home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/BlocksV2.uproject -TargetType=Editor -Progress
Log file: /home/erindel/src/UnrealEngine-5.4.0-release/Engine/Programs/UnrealBuildTool/Log.txt
Using 'git status' to determine working set for adaptive non-unity build (/home/erindel/src/UnrealEngine-5.4.0-release).
Creating makefile for BlocksV2Editor (no existing makefile)
Library 'stdc++' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning. 
Library 'supc++' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning. 
@progress push 5%
Parsing headers for BlocksV2Editor
  Running Internal UnrealHeaderTool /home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/BlocksV2.uproject /home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Intermediate/Build/Linux/BlocksV2Editor/Development/BlocksV2Editor.uhtmanifest -WarningsAsErrors
Total of 46 written
Reflection code generated for BlocksV2Editor in 2.0459662 seconds
@progress pop
------- Build details --------
Using toolchain located at '/home/erindel/src/UnrealEngine-5.4.0-release/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v22_clang-16.0.6-centos7/x86_64-unknown-linux-gnu'.
Using clang (/home/erindel/src/UnrealEngine-5.4.0-release/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v22_clang-16.0.6-centos7/x86_64-unknown-linux-gnu/bin/clang++) version 'clang version 16.0.6 (github.com/llvm/llvm-project 7cbf1a2591520c2491aa35339f227775f4d3adf6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/erindel/src/UnrealEngine-5.4.0-release/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v22_clang-16.0.6-centos7/x86_64-unknown-linux-gnu/bin' (string), 16 (major), 0 (minor), 6 (patch)
Using bundled libc++ standard C++ library.
Using lld linker
Using llvm-ar (/home/erindel/src/UnrealEngine-5.4.0-release/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v22_clang-16.0.6-centos7/x86_64-unknown-linux-gnu/bin/llvm-ar) version 'LLVM (http://llvm.org/):
  LLVM version 16.0.6
  Optimized build. (string)'
Using fast way to relink  circularly dependent libraries (no FixDeps).
Targeted minimum CPU architecture: None
------------------------------
Building BlocksV2Editor...
Determining max actions to execute in parallel (16 physical cores, 22 logical cores)
  Executing up to 16 processes, one per physical core
  Requested 1.5 GB memory per action, 17.66 GB available: limiting max parallel actions to 11
Using Parallel executor to run 6 action(s)
------ Building 6 action(s) started ------
[1/6] Compile BlocksV2.cpp
[2/6] Compile MyClass.cpp
[3/6] Compile Module.AirSim.cpp
In file included from /home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Intermediate/Build/Linux/x64/UnrealEditor/Development/AirSim/Module.AirSim.cpp:46:
/home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Source/UnrealImageCapture.cpp:150:30: warning: 'CompressImageArray' is deprecated: Please use PNGCompressImageArray or ThumbnailCompressImageArray Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
                FImageUtils::CompressImageArray(SizeX, SizeY, RefBitmap, last_compressed_png);
                             ^
/home/erindel/src/UnrealEngine-5.4.0-release/Engine/Source/Runtime/Engine/Public/ImageUtils.h:303:2: note: 'CompressImageArray' has been explicitly marked deprecated here
        UE_DEPRECATED(5.1, "Please use PNGCompressImageArray or ThumbnailCompressImageArray")
        ^
/home/erindel/src/UnrealEngine-5.4.0-release/Engine/Source/Runtime/Core/Public/Misc/CoreMiscDefines.h:274:43: note: expanded from macro 'UE_DEPRECATED'
#define UE_DEPRECATED(Version, Message) [[deprecated(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")]]
                                          ^
1 warning generated.
[4/6] Link (lld) libUnrealEditor-AirSim.so
ld.lld: error: undefined symbol: common_utils::FileSystem::createDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
>>> referenced by FileSystem.hpp:69 (/home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Source/AirLib/include/common/common_utils/FileSystem.hpp:69)
>>>               /home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Intermediate/Build/Linux/x64/UnrealEditor/Development/AirSim/Module.AirSim.cpp.o:(RecordingFile::startRecording(msr::airlib::VehicleSimApiBase*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&))
>>> referenced by FileSystem.hpp:63 (/home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Source/AirLib/include/common/common_utils/FileSystem.hpp:63)
>>>               /home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Intermediate/Build/Linux/x64/UnrealEditor/Development/AirSim/Module.AirSim.cpp.o:(common_utils::FileSystem::getLogFolderPath(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&))
>>> referenced by FileSystem.hpp:63 (/home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Source/AirLib/include/common/common_utils/FileSystem.hpp:63)
>>>               /home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Intermediate/Build/Linux/x64/UnrealEditor/Development/AirSim/Module.AirSim.cpp.o:(common_utils::FileSystem::getLogFileNamePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool))
>>> referenced 2 more times
ld.lld: error: undefined symbol: common_utils::FileSystem::getExecutableFolder()
>>> referenced by Settings.hpp:57 (/home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Source/AirLib/include/common/Settings.hpp:57)
>>>               /home/erindel/src/oldColosseum/Unreal/Environments/BlocksV2/Plugins/AirSim/Intermediate/Build/Linux/x64/UnrealEditor/Development/AirSim/Module.AirSim.cpp.o:(ASimHUD::getSettingsText(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&))
```

**Comment by etscott** [comment]
I'm trying to triage the same error - have you had any luck?

**Comment by ArciAndres** [comment]
Same error here 😣. Any updates?
